"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import AuthGuard from "@/components/AuthGuard";
import Navbar from "@/components/Navbar/Navbar";
import { usePathname } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  

  const isLoginPage = pathname == "/login";
  return (
    <html lang="en">
      <body className="flex">
        {!isLoginPage && <Navbar />}
        <main className="flex-1 transition-all duration-300">
          <AuthGuard>{children}</AuthGuard>
          <Toaster position="bottom-right" closeButton richColors/>
        </main>
      </body>
    </html>
  );
}
